name: Generate Spring Project

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "New repository name (e.g., my-service)."
        required: true
        type: string
      # base_package:
      #   description: "Base Java package (e.g., com.acme.myservice)."
      #   required: true
      #   type: string
      # application_class:
      #   description: "Main Spring Boot application class (e.g. MyServiceApplication)."
      #   required: true
      #   type: string
      visibility:
        description: "public or private."
        required: true
        default: "public"
        type: choice
        options: [public, private]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout generator repo (this repo)
        uses: actions/checkout@v4
        with:
          path: generator

      - name: Checkout template repo
        uses: actions/checkout@v4
        with:
          repository: Kaleb9301/spring-template
          path: template

      - name: Rewrite package/class/pom.xml
        run: |
          chmod +x "${GITHUB_WORKSPACE}/generator/scripts/generate.sh"
          # Convert repo name → safe package (replace - with _)
          SAFE_NAME=$(echo "${{ inputs.repo_name }}" | tr '-' '_')
          BASE_PACKAGE="com.bankofabyssinia.${{ inputs.repo_name}}"
      
          # Convert repo name → PascalCase (SpringTemplate)
          APP_NAME=$(echo "${{ inputs.repo_name }}" \
            | sed -r 's/(^|-)([a-z])/\U\2/g')
      
          APPLICATION_CLASS="${APP_NAME}Application"
      
          echo "Generated class: ${APPLICATION_CLASS}."
      
          "${GITHUB_WORKSPACE}/generator/scripts/generate.sh" \
            "${GITHUB_WORKSPACE}/template" \
            "${{ inputs.repo_name }}" \
            "${BASE_PACKAGE}" \
            "${APPLICATION_CLASS}"
          
         

      - name: Create new repository and push generated code
        env:
          TOKEN: ${{ secrets.REPO_TOKEN }}
          OWNER: Kaleb9301
          REPO: ${{ inputs.repo_name }}
          VIS: ${{ inputs.visibility }}
        run: |
          set -euo pipefail
          api="https://api.github.com"

          echo "Creating repo ${OWNER}/${REPO} (${VIS})"

          payload="{\"name\":\"${REPO}\",\"private\":$( [ "${VIS}" = "private" ] && echo true || echo false )}"

          resp="$(curl -sS -w '\n%{http_code}' -X POST \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "${api}/user/repos" \
            -d "${payload}")"

          body="$(echo "$resp" | head -n -1)"
          code="$(echo "$resp" | tail -n 1)"

          echo "HTTP ${code}"
          echo "${body}"

          if [[ "${code}" != "201" ]]; then
            echo "Repository creation failed"
            exit 1
          fi

          sleep 3
